
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.url=https://kabfiwbztjbaibcqjukn.supabase.co
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.bucket=files

server.port=${PORT:8080}